# Introduction to Python

part 3 

- 引入套件numpy、scipy、matplotlib

- numpy
  - 數學函式庫
  - 1D 陣列的取值與運算
  - 2D 陣列
  - 亂數
  - (數值)檔案的存取

#### 參考資料

- [炎龍老師的教學研究網](http://yenlung.km.nccu.edu.tw/home/index.php?f=contentShow&id=424)
- [手把手打開 Python 資料分析大門](http://foundation.datasci.tw/py3-data-analysis-171217/)
- [The Python Tutorial](https://docs.python.org/3.6/tutorial/index.html)
- [Numpy](http://www.numpy.org/)
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [TutorialsPoint NumPy 教程](https://legacy.gitbook.com/book/wizardforcel/ts-numpy-tut/details)
- [SciPy Cookbook](http://scipy-cookbook.readthedocs.io/index.html)

## 套件讀入方式 1


`from 套件 import 指定函數`


以後就可以直接用引入的函數，比如說:


`from numpy import sin`


以後可直接用 sin 函數。

有些時候用:


`from 套件 import *`


就是套件內所有函數都進來。 『**不建議**』

## 套件讀入方式 2

第二個方式是多數人使用的方式:

`import numpy`

這樣可以不用先計畫好到底要哪些函數，全都可以用而且也不會亂掉。

因為比如要算 sin(3)，要輸入

`numpy.sin(3)`


- Python 有提供縮寫，可以喜歡怎麼叫就怎麼叫

寫成 `import numpy as np`

之後就可以用

`np.sin(3)`

或者將指定函數改名

`from numpy import sin as SIN`

`SIN(3)`

## 起手式
` # encoding : UTF-8`

`% matplotlib inline` 

`import numpy as np`

`import scipy as sp`

`import matplotlib.pyplot as plt`

In [1]:
# encoding : UTF-8

%matplotlib inline

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

# NumPy arrays

### Python objects
- high-level number objects: integers, floating point
- containers: lists (costless insertion and append), dictionaries (fast lookup)

### NumPy provides

- extension package to Python for multi-dimensional arrays
- closer to hardware (efficiency)
- designed for scientific computation (convenience)
- Also known as array oriented computing

# Numpy

- Python 內建的list資料結構不適合數值運算
    - list 可以動態增加減少元素
    - numpy 產生的是固定大小的array，運算上會比python內建的list快很多


- Python 內建的range()函數無法以浮點數來設定序列間距

## 常用的 Numpy 數學函數庫


`sin(x)`
`cos(x)`
`tan(x)`
`arcsin(x)`
`arccos(x)`
`arctan(x)`

`hypot(x1, x2)`:return its hypotenuse = sqrt(x1*x1 + x2*x2) 

`arctan2(x1, x2)`:Element-wise arc tangent of x1/x2 choosing the quadrant correctly.

`exp(x)`:Calculate the exponential of all elements in the input array.

`expm1(x)`:Calculate exp(x) - 1 for all elements in the array.

`exp2(x)`:Calculate 2\*\*p for all p in the input array.

`log(x)`:Natural logarithm, element-wise.

`log10(x)`:Return the base 10 logarithm of the input array, element-wise.

`log2(x)`:Base-2 logarithm of x.

`i0(x)`:Modified Bessel function of the first kind, order 0.

`sinc(x)`:Return the sinc function.

`sqrt(x)`:Return the positive square-root of an array, element-wise.

`cbrt(x)`:Return the cube-root of an array, element-wise.

`square(x)`:Return the element-wise square of the input.

`absolute(x)`:Calculate the absolute value element-wise.

`fabs(x)`:Compute the absolute values element-wise.


[https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.math.html ](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.math.html)

In [2]:
A = list(range(1,10, 0.1))
print(A)   
# range 不支援浮點數

TypeError: 'float' object cannot be interpreted as an integer

In [3]:
import numpy as np

A = np.arange(1, 2, 0.1)      # 從 1 開始，到 2以前(不包含末數)，間隔 0.1

B = np.linspace(0, 10, 5)     # 有含末數  
                              # 從 0 開始，到 10，等距分出 5個數字 
                              # 省略 5則會回到預設的 100
        
#B2 = np.linspace(1, 10, 1, endpoint=False)  #不含末數

        
C = np.logspace(-2, 3, 5)    # 從 10^-2 開始，到 10^3，等距(指數)分出 5個數字
                              # 省略 5則會回到預設的 50

#C2 = np.logspace(-2, 3, 5, base=2)   #以2為底

init_A = np.zeros(10)         # 產生 10 個零
init_B = np.ones(10)          # 產生 10 個 1
init_C = np.empty(5)          # 產生 5 個數（沒指定數值）
init_D = np.full(5,np.pi)     # 產生 5 個 pi

Deg = np.arange(13.) * 30     #產生(0~12)*30 個角度
Rad = np.radians(Deg)         #將角度轉弧度

print(A)
print(B)
print(C)
print(init_A)
print(init_B)
print(init_C)
print(init_D)

print(Deg)
print(Rad)


[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[ 0.   2.5  5.   7.5 10. ]
[1.00000000e-02 1.77827941e-01 3.16227766e+00 5.62341325e+01
 1.00000000e+03]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-2.   -0.75  0.5   1.75  3.  ]
[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
[  0.  30.  60.  90. 120. 150. 180. 210. 240. 270. 300. 330. 360.]
[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653
 6.28318531]


## time
計時工具

- 用 `%%time` 顯示目前cell執行所花的時間 

- 用 `%%timeit` 預設執行10萬次，回傳統計結果

 -在編輯器執行只須`%timeit`或 `from timeit import default_timer` 使用 timer() 輸出時間

In [4]:
%%time
a = [x**2 for x in range(100000)]

Wall time: 49.9 ms


In [5]:
%%timeit 
b = [x**2 for x in range(100000)]

37.9 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%%timeit
#使用list
L = range(10000)
a2 = [i**2 for i in L]   

3.79 ms ± 206 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%%timeit
# 使用 numpy
import numpy as np
L2 = np.arange(10000)
a3 = L2**2

16.4 µs ± 1.4 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 陣列的運算

In [8]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [9]:
a.ndim #維度

1

In [10]:
a.shape 

(3,)

In [11]:
len(a)   #長度

3

In [12]:
a+5  

array([6, 7, 8])

In [13]:
b*3

array([12, 15, 18])

In [14]:
2**a

array([2, 4, 8], dtype=int32)

In [15]:
# 以下運算非矩陣運算

A = np.add(a, b)      #相加
B = np.subtract(a, b) #相減
C = np.multiply(a, b) #相乘
D = np.divide(a, b)   #相除
E = np.negative(a)    #取負號
F = np.power(a, b)    #指數 a的 b次方
                
#print(A ,end=',')      #end=',' 表示不換行，分隔符號為 ,
#print(B)

print(A, B, C, D, E, F, sep='\n')  # sep 為分隔符號 \n表示換行

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-1 -2 -3]
[  1  32 729]


In [16]:
weight = a * b
weight.sum()

32

In [17]:
np.dot(a,b) #內積

32

In [18]:
# 陣列內的運算

import numpy as np

x = np.array([1,2,7,5])

In [19]:
print(x.mean())     #平均值

print(np.median(x)) #中位數

print(x.std())  #標準差

print(x.min())  #最小值
print(x.max())  #最大值

print(x.argmin()) #最小值的index
print(x.argmax()) #最大值的iindex

3.75
3.5
2.384848003542364
1
7
0
2


In [20]:
# 將陣列值輸入函數，輸出陣列函數值

import numpy as np

a = np.arange(5)

print(np.sin(a))
print(np.log(a))    # Natural logarithm
print(np.log10(a))  # the base 10 logarithm 
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[      -inf 0.         0.30103    0.47712125 0.60205999]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log10
  if __name__ == '__main__':


##  array 的取值

In [21]:
import numpy as np

c = np.arange(10)

print(c)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
c [2:9:1]  # index2~9 每隔 3 個取值

array([2, 3, 4, 5, 6, 7, 8])

In [23]:
c [3:]    #取出index＝3之後

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
c [:4]    #取出index＝4之前

array([0, 1, 2, 3])

In [25]:
c [::2]  # 每隔2個index取值

array([0, 2, 4, 6, 8])

In [26]:
c[::2]+=3 # 每間隔2個index 都加 3
print(c)

[ 3  1  5  3  7  5  9  7 11  9]


In [27]:
# 輸入位置的 array取值

c[[2,5,1,8]]

# 等同於 c[np.array([2,5,1,8])]

array([ 5,  5,  1, 11])

In [28]:
c[[2,3,2,4,2]]  # 可重複取值

array([5, 3, 5, 7, 5])

In [29]:
c[[9,7]]=-10 # 指定index 9,7 的值為-10
print(c)

[  3   1   5   3   7   5   9 -10  11 -10]


In [30]:
c[[2,3,2,4,2]]+=1 #index 2,3,2,4,2 各加 1
print(c)

[  3   1   6   4   8   5   9 -10  11 -10]


# 2 維陣列

2 維陣列：先列、後⾏

## np.array ( [row 列]  , [column行] )

In [31]:
import numpy as np

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [32]:
a2.ndim 

2

In [33]:
a2.shape # (列，行)

(2, 3)

In [34]:
len(a2) # returns the size of the first dimension

2

In [35]:
a2.reshape(3,2) #改變行列數

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a2.ravel()   #拉平

array([1, 2, 3, 4, 5, 6])

In [37]:
a2.T  # 轉置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
a2.T.ravel()   # Higher dimensions: last dimensions ravel out “first”.

array([1, 4, 2, 5, 3, 6])

In [39]:
# 可用 numpy 的功能先創造一串數字，再變成陣列 
import numpy as np

a3 = np.arange(10)
print(a3)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
a3.shape

(10,)

In [41]:
a3.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
import numpy as np

a4 = np.zeros((3,3))  #產生3*3都是零的陣列 ps:(3,3)是 tuple
a5 = np.ones((4,4))   #產生4*4都是1的陣列

a6 =  np.eye(3)       #產生3*3，對角都是1的陣列
                      #與 np.idenity 相同

a7 = np.diag(np.linspace(0, 2, 5)) #產生4*4只有對角有值的陣列，對角值為0~2間的5個值
a8 = np.diag(a7) # 取出對角值

print(a4, a5, a6, a7, a8, sep='\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  1.  0.  0. ]
 [0.  0.  0.  1.5 0. ]
 [0.  0.  0.  0.  2. ]]
[0.  0.5 1.  1.5 2. ]


# 2D array 的取用

<img src="./images/np_slicing.png" width=500, height=1000>


# 2D array運算 
axis  指運算的⽅向

在⼆維陣列有兩個⽅向: 

沿列  (axis=0)  
沿⾏  (axis=1) 

<img src="./images/axis1.png" width=300, height=600>

![axis01](./images/axis01.png)
![axis02](./images/axis02.png)

In [43]:
import numpy as np

A = np.arange(10).reshape(2,5) #產生0~9共10個數字，並將其指定為2*5 陣列
print(A) 

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [44]:
C0 = A[:,0] #取出index(行)=0
C1 = A[:,2] #取出index(行)=2

print(C0)
print(C1)

[0 5]
[2 7]


In [45]:
As = A.sum()      # 全部的元素加起來

A0 = A.sum(axis=0)  # 將 axis=0（行）加總
A1 = A.sum(axis=1)  # 將 axis=1 (列) 加總

a0 = A[:,0].sum()  #將index(行)=0的加總
a1 = A[:,3].sum()  #將index(行)=3的加總

print(As)
print(A0)
print(A1)
print(a0, a1, sep='\n')

45
[ 5  7  9 11 13]
[10 35]
5
11


In [46]:
import numpy as np

B = np.array([[1,2,3], [5,6,1]])
print(B)


print(np.median(B, axis=-1)) # last axis的中位數

print(np.argmin(B,axis=0)) # Returns the indices of the minimum values along an axis.
print(np.argmax(B,axis=0)) # Returns the indices of the max values along an axis.


[[1 2 3]
 [5 6 1]]
[2. 5.]
[0 0 1]
[1 1 0]


In [47]:
B2 = np.ones((3,3))

print(B2*B2)
print(np.dot(B2,B2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


# 增加axis

In [48]:
import numpy as np
C = np.array([1,2,3])
print(C)

[1 2 3]


In [49]:
C.shape

(3,)

In [50]:
C2 = C[:, np.newaxis] #增加一個axis，變為2D array

In [51]:
C2.shape

(3, 1)

In [52]:
C3 = C[np.newaxis,:]
print(C3)
print(C3.shape)

[[1 2 3]]
(1, 3)


# Fancy Indexing

In [53]:
# 給定index陣列取值
import numpy as np
D = np.arange(10)
idx = np.array([[3,4],[9,7]])

print(D)
print(D[idx])

[0 1 2 3 4 5 6 7 8 9]
[[3 4]
 [9 7]]


In [54]:
E = np.arange(12).reshape(3,4)

i = np.array([0,1,1,2])
j = np.array([2,1,3,3])

print(E)
print(E[i,j])  #取出(0,2)、(1,1)、(1,3)、(2,3)的值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5  7 11]


In [55]:
F = np.arange(12).reshape(3,4)

i = np.array([[0,1],[1,2]])
j = np.array([[2,1],[3,3]])

print(F)
print(i)
print(j)
print(F[i,j])  #取出(0,2)、(1,1)、(1,3)、(2,3)的值
print(F[i,2])  #取出(0,2)、(1,2)、(1,2)、(2,2)的值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [1 2]]
[[2 1]
 [3 3]]
[[ 2  5]
 [ 7 11]]
[[ 2  6]
 [ 6 10]]


## Fancy indexing 圖例說明
<img src='.\images\fancyindexing.png' width=600, height=500>

In [56]:
# array  過濾器
# 輸入位置的 array取值
# fancy indexing

import numpy as np
L = np.array([3, -2, -1, 5, 7, -3])

print(L)
print(L>0)
print(L[L>0])

[ 3 -2 -1  5  7 -3]
[ True False False  True  True False]
[3 5 7]


In [57]:
# sort
G = np.array([[4, 3, 5], [1, 2, 1]])
H = np.sort(G, axis=1)  #對 axis=1 排序
 
print(G)
print(H)

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]


In [58]:
#利用fancy indexing 排序

I = np.array([4, 3, 1, 2])
J = np.argsort(I)  # 傳回各index的序號

print(I)
print(J)
print(I[J])

[4 3 1 2]
[2 3 1 0]
[1 2 3 4]


# Broadcasting

generate arrays with the same sizes

- Basic operations on numpy arrays (addition, etc.) are elementwise
- This works on arrays of the same size.
 Nevertheless, It’s also possible to do operations on arrays of different
 sizes if NumPy can transform these arrays so that they all have
 the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:    
<img src=".\images\broadcasting.png" width=600, height=600 >

In [59]:
import numpy as np

A = np.arange(0,40,10)
print(A)
print(A.shape)

[ 0 10 20 30]
(4,)


In [60]:
A = A[:, np.newaxis]

print(A)
print(A.shape)

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [61]:
B = np.array([0,1,2])

print(A+B)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [62]:
# 可以合併在一行內

import numpy as np

C = np.arange(6)
D = np.arange(0,51,10)

print(C)
print(D)

CD = C + D[:,np.newaxis]
print(CD)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


# meshgrid 

- 將原生數值變成格點

- 讓`等高線圖(contour)`、`向量箭頭圖(quiver)`、`流線圖(streamplot)`、`3D 圖(mplot3d)` 可吃的格式

In [63]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

X, Y = np.meshgrid(x, y)

distance = np.sqrt(X**2 + Y**2)

print(x)
print(y)

print(X)
print(Y)

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]


## ogrid and mgrid

mgrid 與meshgrid類似，但mgrid不是函數，meshgrid要以一維數組為對象，而mgrid直接用[]產生

ogrid 與mgrid類似，但傳回的是稀疏的陣列

In [64]:
import numpy as np

xm, ym = np.mgrid[0:5,0:5]

print(xm)
print(ym)

print(np.sqrt(xm**2+ym**2))

zm = np.mgrid[-1:1:5j]

print(zm)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0.         1.         2.         3.         4.        ]
 [1.         1.41421356 2.23606798 3.16227766 4.12310563]
 [2.         2.23606798 2.82842712 3.60555128 4.47213595]
 [3.         3.16227766 3.60555128 4.24264069 5.        ]
 [4.         4.12310563 4.47213595 5.         5.65685425]]
[-1.  -0.5  0.   0.5  1. ]


In [65]:
import numpy as np

xo, yo = np.ogrid[0:5,0:5]

print(xo)
print(yo)

distance1 = np.sqrt(xo**2 + yo**2)

print(distance1)
np.ogrid[-1:1:5j] # step length is a complex number

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0.         1.         2.         3.         4.        ]
 [1.         1.41421356 2.23606798 3.16227766 4.12310563]
 [2.         2.23606798 2.82842712 3.60555128 4.47213595]
 [3.         3.16227766 3.60555128 4.24264069 5.        ]
 [4.         4.12310563 4.47213595 5.         5.65685425]]


array([-1. , -0.5,  0. ,  0.5,  1. ])

# 亂數

## import numpy.random.xxx as yyy

- `rand(d0, d1, ..., dn)`	Random values in a given shape.
- `randn(d0, d1, ..., dn)`	Return a sample (or samples) from the “standard normal” distribution.
- `randint(low[, high, size, dtype])`	Return random integers from low (inclusive) to high (exclusive)
- `random_integers(low[, high, size])`	Random integers of type np.int between low and high, inclusive
- `random_sample([size])`	Return random floats in the half-open interval [0.0, 1.0)
- `random([size])`	Return random floats in the half-open interval [0.0, 1.0)
- `ranf([size])`	Return random floats in the half-open interval [0.0, 1.0)
- `sample([size])`	Return random floats in the half-open interval [0.0, 1.0)
- `choice(a[, size, replace, p])`	Generates a random sample from a given 1-D array

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [66]:
import numpy.random as npr

print(npr.rand(5))  # 0~1(不包含1)間，隨機 5個數字
print(npr.rand(3,2)) # 產生3*2陣列，數字由0~1(不包含1)間隨機組成
  

print(npr.randint(0, 3, 50))  # 在 0~3 (不包含3) 隨機 50 個整數亂數
print(np.random.randint(5, size=(2, 4))) # 0~5間取亂數，組成2*4陣列
    
print(npr.randn(10))  # 高斯分佈(mean=0，variance=1)，隨機取10個值

print(np.random.normal(loc=0, scale=1, size=10)) #常態分佈 loc：mean，scale：std，size:shape

print(np.random.uniform(low=0.0, high=1.0, size=10))
# Samples are uniformly distributed over the half-open interval [low~high)

[0.42650304 0.59875585 0.13088785 0.70503317 0.04782052]
[[0.39032389 0.48126486]
 [0.75016791 0.59406353]
 [0.91285425 0.64226443]]
[0 0 1 0 1 2 2 1 0 2 0 1 2 2 0 2 0 2 2 2 2 1 0 0 0 2 2 2 2 2 1 0 2 0 1 2 1
 2 1 2 2 0 1 2 1 1 0 2 0 1]
[[0 2 1 2]
 [2 3 2 4]]
[-0.4990894  -0.18014838  0.66514833 -0.22883387 -0.04620667 -0.75055012
 -0.16392584 -2.56877826  0.43958687  1.18877922]
[-1.25300241  1.26581465  0.40239014 -0.030429    0.44136698 -0.45124617
 -1.73194056  0.31658986  0.05181305  0.38303404]
[0.11896762 0.59755543 0.00687148 0.26867754 0.79665645 0.38094568
 0.55099956 0.78439586 0.95465106 0.66307463]


# 資料存取 loading data files (text files)


 `np.savetxt('<path>', <data_array>)` 存檔

 `np.loadtxt('<path>')` 讀檔 ，有 # 的列不會讀取


In [67]:
import numpy as np

raw = np.array(np.arange(6))

print(raw)

np.savetxt('.\savetxt.txt', raw)

data0 = np.loadtxt('.\savetxt.txt')
                        
print(data0)

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]


In [68]:
# 一般常用的數據檔會有多行，則讀檔時需要用多個變數承接

raw = np.array([[np.arange(6)], [np.arange(6)**2]]).reshape(6,2)

print(raw)

np.savetxt('.\savetxt.txt', raw)


data0, data1 = np.loadtxt('.\savetxt.txt', unpack=True)

# unpack : bool, optional
#If True, the returned array is transposed, so that arguments may be unpacked using x, y, z = loadtxt(...). 
#When used with a structured data-type, arrays are returned for each field. Default is False.
                        
print(data0)
print(data1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  1]
 [ 4  9]
 [16 25]]
[ 0.  2.  4.  0.  4. 16.]
[ 1.  3.  5.  1.  9. 25.]
